[package]
name = "postgresfixture"
version = "0.1.0"
authors = ["Gavin Panella <gavinpanella@gmail.com>"]

[lib]
name = "postgresfixture"
path = "src/lib.rs"

[[bin]]
name = "postgresfixture"
path = "src/main.rs"
doc = false

[dependencies]
clap = "^2.24.2"
nix = "^0.17.0"
postgres = "^0.17.2"
regex = "^1.3.4"
shell-escape = "^0.1.3"

[dev-dependencies]
tempdir = "^0.3"
